services:
  - type: web
    name: menu-upload-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    disk:
      - name: uploads
        mountPath: /opt/render/project/src/uploads
        sizeGB: 1
      - name: data
        mountPath: /opt/render/project/src/data
        sizeGB: 1 